### ISSUE TITLE
Curation FLAGGED column described incorrectly

### ISSUE THREAD

**Issue by tedtoal** [lima1/PureCN#114]
In section 7 of the PureCN overview pdf file, on Curation, it says:

> PureCN currently only flags samples with warnings, it does not mark any samples as failed. The Failed column in the curation file can be used to manually flag samples for exclusion in downstream analyses. See Table 5 for an explanation of all flags.

First, I see that many of my samples have TRUE in the FAILED column, which I would interpret as PureCN having marked it as failed.

Second, even though this column has TRUE in it, as far as I can tell PureCN did not exclude it from any analyses.  By "downsteam analyses" do you mean "downstream analyses performed after PureCN analysis"?  (Because I thought it referred to subsequent PureCN analyses such as Dx.R).

Third, Table 5 does not have the FAILED column in it.

**Comment by lima1** [comment]
Are you sure you get TRUE in the failed column? I don't see a way that is possible (see https://github.com/lima1/PureCN/blob/master/R/createCurationFile.R). 

I guess many of your samples are flagged? The flagging is definitely too liberal and is on my TODO list for the next release.

FAILED is only used by callAlterations IIRC because this function is very sensitive to incorrect purity/ploidy.  Dx.R is inherently more robust here.

**Comment by tedtoal** [comment]
Yes, you're right, they aren't marked FAILED, they are marked as FLAGGED.  I see that the FLAGGED column is also not in Table 5.  I just now realized that probably what it means is that one or more of the other flag columns is true, is that right?

**Comment by lima1** [comment]
Yes, that's correct.
