### ISSUE TITLE
Using PureCN in the bcbio workflow

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#123]
Hi Markus,

I just wanted to get your opinion of using PureCN as part of the bcbio workflow. From my understanding this is going to produce suboptimal results as no mapping bias file / PON data is added. I saw another thread talking about off target reads I assume with enough off target reads you can maybe increase the number of SNPs you detect? 

1) I am just curious if you think this is a viable workflow (given it is very convenient) and 2) what conditions you would require for acceptable results ie. higher depth of off-target coverage etc.

3) If I was to use a custom panel with tiling of SNPs would this make the bcbio workflow version more viable?

Ultimately, I would still want to use the full workflow you describe in your package but it would be great to have an idea of how much worse off I'll be and how I can minimise this.

**Comment by lima1** [comment]
Hi Warren,

trying the bcbio is on my TODO list. I'm not sure how much better our best practices are. My guess is for small panels, it's probably worth trying PureCN directly first, and I'm more than happy to contribute to bcbio if you see a big improvement over it.

But to answer your questions:

off-target is mostly useful for small panels to fill the gaps between targeted genes and therefore get a more accurate ploidy by increasing coverage data points. Since CNVkit uses off-target reads, this should be fine.

PureCN will automatically add SNPs in the flanking regions. By default, that's 50bp, but these "shoulders" can be large in high depth data, so increasing to 100-200bp can be worth it. Should be easy to change/add this in bcbio

If you have a nice tiling of SNPs, then off-target reads become less important for ploidy. PureCN will list the log2-ratio tumor vs normal noise for both on- and off-target. If off-target noise and the number of on-target intervals is high, you can safely ignore off-target.

Yes, I would highly recommend the mapping bias file, especially for tumor-only.

Markus

**Comment by waemm** [comment]
Thanks Markus, I am currently testing the PureCN output from bcbio. I am not sure it is really ready, some output seems to be missing and purity estimates are quite different from the standard workflow. It doesn't look like there are parameters to include mapping bias files or panel of normals either.

**Comment by lima1** [comment]
Feel free to send me log-files and BAF-plot (https://scfbm.biomedcentral.com/articles/10.1186/s13029-016-0060-z/figures/3) of 1-2 examples where they differ. It's usually quite obvious who is right and how good it is given the quality of the data.
