### ISSUE TITLE
PureCN Input for Clonality Analysis

### ISSUE THREAD

**Issue by mgfield** [lima1/PureCN#126]
There is the ability to get purity, ploidy, and major and minor copy numbers with this software, which sets it up perfectly to use output for subclonal clustering.  However, I have not been able to easily figure out how to format the data properly for input into TitanCNA, phylowgs, etc.  This would be particularly helpful for cases that do not have matched normal that can still be analysed with PureCN or for using CNVKit segmentation through PureCN.  Do you have any scripts or pipelines that are available to assist with this?  

SuperFreq has come out recently that claims to be able to use tumor only or matched samples and conduct CNV calling, subclonal clustering, and clonality calls.  I have not used that yet but would like to compare the different toolkits and was hoping to use PureCN in my analysis. 

Thanks.

**Comment by lima1** [comment]
Hi,

have a look at section 6.2.1 of the vignette. This should provide for each variant all the information you need. (It provides you even cancer cell fractions + CIs, but yeah, subclonal clustering should give you more accurate CCFs.).  PureCN is similar to TitanCNA, albeit with a simplified likelihood model to make it tractable for tumor-only. Would be curious to hear your experience with tools like sciclone, pyclone, phylowgs and PureCN input.

Since we use PureCN almost exclusively for smaller targeted panels and mostly cfDNA where this is pretty challenging, I never really tried the clustering myself.

SuperFreq is good and as I understand designed for this task.

Sorry I can't be more helpful.

Best,
Markus
