### ISSUE TITLE
Manual curation using flags

### ISSUE THREAD

**Issue by dongjoban17** [lima1/PureCN#138]
Hello again,

My samples (whole-exome sequencing; >100x; ovarian cancer) are have been flagged with the following (ordered from most occurring):

- NOISY LOG-RATIO (~95% of the samples)
- HIGH AT- OR LOW GC-DROPOUT (~65% of the samples)
  - Per sequence GC-content is > 60% for normal samples, deviating from the expected %.
  - Downloaded normal samples (males) from SRA to match the exome kit used (Agilent Sureselect v7).
- POOR GOF (~13% of the samples)
  - Fit % values range from 65-75%
- NOISY SEGMENTATION (~10% of the samples)
  - Followed vignette using Coverage.R
- RARE KARYOTYPE

I've gone through the FAQ section in the user manual including "Questions related to manual curation" and haven't been able to come to a good conclusion for a 1st-pass filtering. I think the noisy signals could be due to the apparent genomic instability observed in ovarian cancer, but any advice would be greatly appreciated.

Thanks!

**Comment by lima1** [comment]
If most are flagged as noisy, there is probably a problem with the setup. Can you send an example of the log file and the B-allele frequency plot (the 3 panels in Sampleid.pdf of the top solution).

**Comment by dongjoban17** [comment]
Hi Markus,

Here are the files you asked for. Let me know if you need more sample files.
[purecn_example.zip](https://github.com/lima1/PureCN/files/5143383/purecn_example.zip)

**Comment by lima1** [comment]
Nothing obvious wrong with the setup. You can use PSCBS instead of the DNAcopy default:

In R:
`BiocManager::install("lima1/PSCBS", ref="add_dnacopy_weighting")`

Then add --funsegmentation PSCBS in PureCN.R. This will also use the SNPs for segmentation.

Are these old FFPE samples? The coverage normalization/denoising didn't work well. A standard deviation of 0.8 is pretty bad. Clean, high quality, deep sequencing data has less than 0.2. 150X WES should probably be around  0.25 to 0.35. 

Either the tumors are indeed noisy or it's an issue with the SRA normals.

**Comment by dongjoban17** [comment]
Tumors were sequenced last year and the normals I downloaded were added to SRA in early 2020. I downloaded the raw fastq files and QC'd them to make sure they were okay in terms of quality prior to alignment workflow. As I mentioned in my OG post, all of the normals either failed or gave warning for per sequence QC-content (cause for AT-dropout?). There's a limited number of normal samples that has a matching exome kit (5/33 after QC) so I don't think I can test to rule out whether normals are causing issues downstream.

I'll try to re-run the samples with PSCBS and report back here. What's a good cutoff for SD in terms of coverage normalization?

**Comment by lima1** [comment]
Age: samples can be pretty old when they are sequenced. If you have time of biopsy, anything older than 3-4 years can be noisy. But yes, I suspect the normals are the culprit. 

Can you point me again to the normal failures? I can't remember. 

PSBCS: Increase of SD in segmentation is expected in this case. The noise will lead to oversegmentation; PSCBS might be a bit better since it looks at SNPs, which shouldn't be affected by coverage noise (noise affects both alleles equally).

Cutoff for SD? You mean to say a sample failed QC or something? I would say 0.45 or higher. For older FFPE, it's not always avoidable. Ovarian has high purity, so more signal in the noise.

The interval version isn't too important. You might miss some genes or some genes that are missing are skipped over. Important is that the normals and tumors are essentially sequenced with the same assay. Otherwise the baseline for the tumor normalization is off and you get a noisy profile.

**Comment by dongjoban17** [comment]
Thank you for your feedback Markus. 

Is there a way to force the parameter of `max.segments` in an attempt to reduce noise? My naïve assumption is that if `max.segments` parameter is reduced (hence increasing the length of the segments), then there will be a reduction in resolution but also will lessen the noise present.
 
Regarding your comment on the quality of the normal samples, please refer to GC-content plots from MultiQC (top: normals; bottom: tumors). I selected samples with warning and pass labels from the available normal samples to create normalDB, but they also look problematic.

![gc_content_normals](https://user-images.githubusercontent.com/14929596/91624681-8cbc1700-e96f-11ea-9907-299a0f711e1e.png)
![gc_content_tumors](https://user-images.githubusercontent.com/14929596/91624688-934a8e80-e96f-11ea-8583-5e7bbd253a53.png)

**Comment by lima1** [comment]
Wow, that is a weird GC profile. You can make the segmentation more conservative, but that’s a bss as band aid at best. PSCBS with low alpha and high Undosd is all you can do. Results won’t be pretty, but maybe good enough for what you need it if you’re lucky...

**Comment by dongjoban17** [comment]
This will sound a little off, but do you think it's "better" to have the current noise due to poor normal samples than the noise from running other normal samples with lower version of the assay (v7 -> v6)?

**Comment by lima1** [comment]
That’s possible. I would probably not use offtarget, since some could be ontarget in the other assay. I think I once tried v6 with v4 normals and the SD roughly doubled, like 0.6. Not good, but useable for basic purity and amplification calling. 

Maybe also increase minmappability in IntervalFile.R. This should ignore baits in difficult regions that might be different across assays.

**Comment by dongjoban17** [comment]
Running IntervalFile.R with `--minmappability 0.7,0.1,0.9` and without `--offtarget` does decrease the SD of log-ratio slightly, but it's still very noisy. I'm open to any other routes that I might be able to try. 

If not, I wonder what data from running PureCN.R I can actually use at this point. Originally, I was primarily interested in sub-clonal and clonal status, somatic status, and tumor purity.

**Comment by lima1** [comment]
Before giving up, I would probably try a new set of normals, even if it is v6.  Maybe it is also worth asking Agilent if they have v7 normal BAMs they are willing to share. I know from other users that some vendors do that.

Difficult to say if good enough. Tumor purity is usually obvious in a visual check if it's roughly right, when the main copy number states (single loss, normal, single gain, double gain, ...) appear to be captured correctly.

Somatic status is difficult in high purity ovarian samples (see our JCO CCI paper), sub-clonal status is in contrast easier.

**Comment by dongjoban17** [comment]
I reached out to them to see if they do have such resources available. In the meantime, I will continue to test more normal samples from SRA. Could you elaborate a little bit on what you mean by " sub-clonal status is in contrast easier"?

Also, I really do appreciate your responses. Please let me know if you'd prefer these discussions to be elsewhere.

**Comment by lima1** [comment]
If possible, download a few normal datasets. I would do a PCA of the coverage files and see which ones are closest to tumors.

Sub-clonal is easier with higher coverage I mean. Assume 100% purity and normal heterozygous. So mono-clonal somatic have 0.5 expected allelic fraction. Sub-clonal in 50% has 0.25 AF. That's a big difference. With 20% purity, you have 0.1 AF vs 0.05 AF. You need a high coverage to distinguish those with confidence.

**Comment by lima1** [comment]
Closing for now, feel free to open if necessary.

**Comment by dongjoban17** [comment]
I was able to reduce the SD of log-ratios for a couple of samples (~0.8-0.9 to ~0.4-0.5) using the demo samples provided by Agilent.

**Comment by lima1** [comment]
That's great to know that Agilent shares demo samples. I would start with all normals, maybe worth trying without the two PC2 outliers. But should not matter too much.

0.4 to 0.5 is getting into usable range, especially with high purity ovarian data.

For coverage normalization, it doesn't matter at all if they are from the same sample. For mapping bias, it's still valuable, but you obviously get fewer number of SNPs. For mapping bias, you can definitely use all normals, even the outliers.

**Comment by dongjoban17** [comment]
I'm currently doing a couple more iterations to see if I can reduce the SD even further. I'll try including other normal samples like you suggested as well. I might have some lingering questions later, but I think I should be good for now. Thanks for your insights and guidance throughout this process.
