### ISSUE TITLE
Determining sample quality

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#144]
Hi Markus,

I recently analysed a tumour sample that has very few somatic variants this is strange given that in similar tumour samples we get ample variants. When I run this sample through PureCN I get very few predicted somatic variants and I include the first segmentation results below. From what I can see the log ratio changes are minimal and it looks like there is very little change across the genome. Is it likely we're just looking at normal tissue here? Are there other values/plots I'm missing that could help me make an assessment here? 

sample info:
"Sampleid","Purity","Ploidy","Sex","Contamination","Flagged","Failed","Curated","Comment"
"HNO.6338375_30001813",0.36,2.98304674298337,"M",0,TRUE,FALSE,FALSE,"NOISY SEGMENTATION"

![image](https://user-images.githubusercontent.com/71687/92701923-7c7d4200-f348-11ea-9b5c-2786e6c79110.png)

![image](https://user-images.githubusercontent.com/71687/92701949-83a45000-f348-11ea-9df3-2f649c1b29f1.png)

![image](https://user-images.githubusercontent.com/71687/92703103-d6323c00-f349-11ea-88da-7094af60424f.png)

**Comment by lima1** [comment]
Hi Warren,

yes, this sample looks pretty bad and the PureCN fit is completely wrong. Can you share the log file of this sample and maybe one of your best quality samples (low log ratio standard deviation? This will help me understand if it's a sample or setup issue.

Best,
Markus

**Comment by waemm** [comment]
Hi Markus, what would you consider a low log ratio sd? also are you referring to 
"SCNA−fit log−likelihood" in the pdf? I just selected 2 samples here that appear to have expected variant numbers etc. 

[sample2.log](https://github.com/lima1/PureCN/files/5202648/sample2.log)
[sample3.log](https://github.com/lima1/PureCN/files/5202649/sample3.log)
[suspect1.log](https://github.com/lima1/PureCN/files/5202650/suspect1.log)

**Comment by lima1** [comment]
Looks like your on-target regions look pretty good (SD < 0.2 is nice), but off-target is noisy. You can try the latest GitHub version that is dealing with this problem of noisy off-target. You can also try increasing the off-target bin size in CNVkit.

I would also highly recommend building the mapping bias database. It usually has a big impact.  Your 7.1% of targets with variants is also low, you probably didn't run Mutect with interval padding right? There are lots of SNPs just outside the exons which you miss without padding.

**Comment by lima1** [comment]
Oh, and I see you have only 70% annotated as known germline. That's pretty low (and explains the huge dark green cloud of novel germline), you probably want to fix that. Current GitHub is smarter in reading the POPAF field and understands it when it's in -log10 scale (as in recent GATK4).

**Comment by waemm** [comment]
Thanks Markus, this is all very helpful and I really appreciate your advice! I'll be adding the mapping bias file and it looks like the capture bed that was run here indeed did not pad the bait regions, I'll replace it and this will hopefully solve the off target noise issues. There has been a major reshuffle of the pipeline so things are a bit disorganised!

Just some final questions: 
1. The novel germ line variants, this is an issue where pureCN doesn't recognise them as known germline from the VCF file but this should be sorted by updating PureCN correct ?
2. What metrics do you use to determine sample quality? I'll be sure to use the SD values from now on as a guide. 
3. Is my assumption correct that if there is very little variance in the log ratios this sample could be mostly healthy tissue?

**Comment by lima1** [comment]
You don't need to pad the BED file, PureCN automatically includes variants in the flanking regions when present. Simply tell the variant caller to pad in interval file (--interval_padding I think in Mutect) so that they are included in the VCF.

1) Yes, current master branch PureCN should be able to understand POPAF. If not, please open a bug report.

2) If you run Picard, noise (the SD) is usually a linear function of duplication rate. So nice samples with lots of input material should look great. High GC or AT drop out also affect the quality since many GC/AT rich regions will have low coverage (also reported in Picard). 

3) In your current setup, PureCN confuses noise with signal and thinks there are CNAs. Properly set up, it should be reliable down to 10-20% tumor, depending on quality. So if there are CNAs. it will find them and report the purity accordingly. And if lower than that, it should tell you it found no CNAs, so the purity estimate is unreliable.

**Comment by lima1** [comment]
Closing for now. Feel free to reopen if necessary.

**Comment by waemm** [comment]
Thank Markus, really appreciate your help as always!
