### ISSUE TITLE
Question. Does NormalDB.R apply minimum genotyped sample filter ?

### ISSUE THREAD

**Issue by Admera2020** [lima1/PureCN#160]
Hello Markus, 

I am trying to create NormalDB. I have a fairly small set of normal samples ( n=6), to make things worse they are from adjacent tissues.   So I suspect there will be some somatic mutation contamination in them. But they should be private to the sample. Curious, what NormalDB would do if a "real somatic" mutation is found in a "single" sample.  Should I filter out calls that are found in say two or fewer individuals before feed in VCF to NormalDB or is this something taken care of by NormalDB? 

I appreciate it if you came across (if at all) any obvious issues with Adjacent Tissue normal besides this?

**Comment by lima1** [comment]
Hi,

it does. The mapping bias function ignores everything below 0.05 allelic fraction. That should exclude most contamination. By default, it will include all variants for the mapping bias calculation, even single sample ones (there is a min.normals parameter though, https://github.com/lima1/PureCN/blob/master/R/calculateMappingBiasVcf.R, might not be available as command line argument in NormalDB.R, so you might need to modify locally if needed). But it will force the mapping bias to something more normal due to the limited evidence. Give it a shot with the default, if your clear somatic mutations have suspiciously large mapping bias (big difference between observed and adjusted allelic fraction), you might want to set min.normals to 2.

Only limited experience otherwise, but no reason why it shouldn't work. I once did a tumor-only vs tumor/normal benchmarking that included adjacent normals and the tumor-only had no issues while the tumor/normal wrongly classified some somatic as germline.

Best,
Markus

**Comment by Admera2020** [comment]
Hello Markus, 

Thank you very much for your quick reply and detailed explanation. 
`The mapping bias function ignores everything below 0.05 allelic fraction.`  that's really helpful. 
I think I will pre-filter VCF before using it for NormalDB.R that way I don't have to mess with the core package. 

Happy Holidays.
