### ISSUE TITLE
Tumor purity of Normal Sample

### ISSUE THREAD

**Issue by jeongmeani** [lima1/PureCN#162]
Hi,

i have normal wes data from tissue, blood and tumor paired wes data of this normal sample.
and i guess that normal tissue samples have some tumor part.
so using tumor-purity analysis, i want to check this.
does it make sense?

actually, i have already analysed this, but even blood normal sample get high score of tumor purity.

Best Regards and Happy new year!

Jeongmin

**Comment by lima1** [comment]
Hi Jeongmin,

PureCN has, partly by design, issues in calculating purity below ~10% (depending on quality).  Stay tuned, we have a preprint and ASCO presentation coming soon in the context of accurately calculating purity in that very low range often observed in cfDNA.

The BROAD has a tool for determining tumor contamination in adjacent normals. I don't have experience with it since we don't use adjacent normals, but that would probably be the much better approach. Let me know if you have trouble finding it.

Cheers,
Markus

**Comment by jeongmeani** [comment]
Ok!

Thank you for reply :)
i try the tool DeTiN.

and i'm looking forward to your plan about cfDNA.

Best Regards.

Jeongmin
