### ISSUE TITLE
validation: can't detect deletions confirmed by ddPCR

### ISSUE THREAD

**Issue by naumenko-sa** [lima1/PureCN#164]
Hi Markus!

Thanks for supporting PureCN!

We are trying to validate a deletion detection in a series of cfDNA samples. 
We have confirmed the deletion by ddPCR and can't pick it up by PureCN 
(native segmentation, PON of 50 process matched samples).

I've tried the default workflow (with mutect2) and also tried to add 
`--minpurity 0.1 --minaf 0.01 --error 0.0005` suggested for cfDNA samples - that did not help.

The purity of the two samples where we are quite confident about the deletion is 0.32 and 0.12.
They have 3-4 variants called in a gene, and none of the variants in PASS mutect filters somatic
(one sample has 3 germline variants, and the other 3 germline + 1 multiallelic/slippage/weak_evidence somatic).

Do you have any suggestions on how to improve sensitivity in that case, or 
there is a principal limitation here - if we have not gotten any trustworthy marker somatic variants in a gene,
then we don't have a chance to pick up a CNV?

Sergey

**Comment by lima1** [comment]
Hi Sergej,

yes, homozygous deletions can be tricky. 0.12 might stretch it, but 0.32 should work.

A few recommendations:

- Use my patched PSCBS with weighting support. In version 1.20.0, this will check if the off-target noise is large and in case it is, will segment once with and once without those regions and will return the intersection of breakpoints. This makes sure that the signal is not diluted by the neighboring noisy regions
- play with the sd.undo segmentation parameter. In general, I'm happy with the default, but maybe you can afford to lower it a bit. so in general, over-segmentation is bad because it lowers the LOH calling sensitivity, but under-segmentation will miss alterations (mostly the very focal homdels). 
- when I design new panels, I try to squeeze in SNP probes close to known deletions. Capturing SNPs helps a lot in calling deletions. if you have a descent coverage, try increasing the padding to 100 or even 200bp to increase the chance of covering SNPs._

If you detect a somatic marker, it's a single copy number loss. Those tend to be larger and are thus usually easier to call, even though the drop in coverage is only half as that of a homdel. 

Markus

**Comment by naumenko-sa** [comment]
Thanks so much for the quick response! 

using ```PureCN.R --funsegmentation PSCBS``` helped to detect a hom deletion in a sample with 0.32 purity.
Even the standard PSCBS package worked! Does it make sense to use PSCBS by default in all projects?

Sergey

**Comment by lima1** [comment]
Glad it worked. Yes PSCBS as default is good. I’ll likely change it for the upcoming release.
