### ISSUE TITLE
Issue Running with cnvkit Data

### ISSUE THREAD

**Issue by drmrgd** [lima1/PureCN#166]
I've tried to follow the use guide for inputting cnvkit segmentation files, but keep running into the following error:

```
Error in if (is.na(posterior) || posterior < 0.5) flag <- TRUE :
  missing value where TRUE/FALSE needed
Calls: runAbsoluteCN ... .calcMsSegment -> lapply -> lapply -> FUN -> .calcMsSegmentC
Execution halted
```

The full log is [here](https://gist.github.com/drmrgd/c2c2c8eacedaf0a598606f7fc35b199b)

I really have no idea where to start troubleshooting this as I don't know what data might be missing and what is expected at this step.  Any help pointing me in the right direction is most appreciated!

**Comment by kristianunger** [comment]
I am experiencing exactly the same error

`INFO [2021-03-16 16:29:35] Fitting variants for purity 0.70, tumor ploidy 4.99 and contamination 0.01.
Error in if (is.na(posterior) || posterior < 0.5) flag <- TRUE :
  missing value where TRUE/FALSE needed
Calls: runAbsoluteCN ... .calcMsSegment -> lapply -> lapply -> FUN -> .calcMsSegmentC` .

by running

`Rscript $PURECN/PureCN.R --out $OUT/$SAMPLEID  \
    --sampleid $SAMPLEID \
    --tumor $cnvkit_cnr \
    --segfile $cnvkit_seg \
    --vcf $vcffile \
    --statsfile $statsfile \
    --snpblacklist $srr \
    --genome hg38 \
    --model=betabin \
    --funsegmentation Hclust \
    --force --postoptimize --seed 123 `


The same happens when using the bam-coverages instead of the CNVkit-cnr files as input. Any help very much appreciated!


sessioninfo:

`sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/zyto/unger/anaconda3/envs/PureCN/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] PureCN_1.20.0               VariantAnnotation_1.36.0
 [3] Rsamtools_2.6.0             Biostrings_2.58.0
 [5] XVector_0.30.0              SummarizedExperiment_1.20.0
 [7] Biobase_2.50.0              GenomicRanges_1.42.0
 [9] GenomeInfoDb_1.26.4         IRanges_2.24.1
[11] S4Vectors_0.28.1            MatrixGenerics_1.2.1
[13] matrixStats_0.58.0          BiocGenerics_0.36.0
[15] DNAcopy_1.64.0

loaded via a namespace (and not attached):
 [1] httr_1.4.2               VGAM_1.1-5               bit64_4.0.5
 [4] splines_4.0.3            assertthat_0.2.1         askpass_1.1
 [7] BiocFileCache_1.14.0     blob_1.2.1               BSgenome_1.58.0
[10] GenomeInfoDbData_1.2.4   progress_1.2.2           pillar_1.5.1
[13] RSQLite_2.2.4            lattice_0.20-41          glue_1.4.2
[16] RColorBrewer_1.1-2       colorspace_2.0-0         Matrix_1.3-2
[19] XML_3.99-0.5             pkgconfig_2.0.3          biomaRt_2.46.3
[22] zlibbioc_1.36.0          purrr_0.3.4              scales_1.1.1
[25] BiocParallel_1.24.1      tibble_3.1.0             openssl_1.4.3
[28] ggplot2_3.3.3            generics_0.1.0           ellipsis_0.3.1
[31] cachem_1.0.4             GenomicFeatures_1.42.2   magrittr_2.0.1
[34] crayon_1.4.1             memoise_2.0.0            fansi_0.4.2
[37] xml2_1.3.2               tools_4.0.3              data.table_1.14.0
[40] prettyunits_1.1.1        hms_1.0.0                formatR_1.8
[43] lifecycle_1.0.0          stringr_1.4.0            Rhdf5lib_1.12.1
[46] munsell_0.5.0            DelayedArray_0.16.2      lambda.r_1.2.4
[49] AnnotationDbi_1.52.0     compiler_4.0.3           rlang_0.4.10
[52] rhdf5_2.34.0             futile.logger_1.4.3      grid_4.0.3
[55] RCurl_1.98-1.2           rhdf5filters_1.2.0       rstudioapi_0.13
[58] rappdirs_0.3.3           bitops_1.0-6             gtable_0.3.0
[61] DBI_1.1.1                curl_4.3                 R6_2.5.0
[64] gridExtra_2.3            GenomicAlignments_1.26.0 dplyr_1.0.5
[67] rtracklayer_1.50.0       fastmap_1.1.0            bit_4.0.4
[70] utf8_1.2.1               futile.options_1.0.1     stringi_1.5.3
[73] Rcpp_1.0.6               vctrs_0.3.6              dbplyr_2.1.0
[76] tidyselect_1.1.0
`

**Comment by lima1** [comment]
@kristianunger, do you also get following in your log file?

INFO [2021-03-15 09:12:32] Mean standard deviation of log-ratios: 0.40
INFO [2021-03-15 09:12:32] Mean standard deviation of on-target log-ratios only: 0.00
INFO [2021-03-15 09:12:32] Mean standard deviation of off-target log-ratios only: 0.00

**Comment by kristianunger** [comment]
@lima1 please find the complete log in the following:

resulting from

Rscript $PURECN/PureCN.R --out $OUT/$SAMPLEID  \
    --sampleid $SAMPLEID \
    --tumor $cnvkit_cnr \
    --segfile $cnvkit_seg \
    --vcf $vcffile \
    --snpblacklist $srr \
    --minpurity=0.8 \
    --maxpurity=0.8 \
    --genome hg38 \
    --model=betabin \
    --funsegmentation Hclust \
    --intervals S07604514_Covered.intervals.txt \
    --force --postoptimize --seed 123 > log



INFO [2021-03-16 21:47:24] Loading PureCN 1.20.0...
INFO [2021-03-16 21:47:25] ------------------------------------------------------------
INFO [2021-03-16 21:47:25] PureCN 1.20.0
INFO [2021-03-16 21:47:25] ------------------------------------------------------------
INFO [2021-03-16 21:47:25] Arguments: -normal.coverage.file  -tumor.coverage.file /home/zyto/unger/WES_Rezidiv_HNSCC_Clonality/PureCN/output/HL02_R1.final.cnr -log.ratio -seg.file /home/zyto/unger/WES_Rezidiv_HNSCC_Clonality/PureCN/output/seg_for_PureCN/HL02_R1.final.seg -vcf.file /home/zyto/unger/WES_Rezidiv_HNSCC_Clonality/mutect2_snakemake/results_arch/HL02_Rez.final/filtered_all.vcf.gz -normalDB  -genome hg38 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.segmentation 0.005,NULL -sampleid HL02_R1.final -min.ploidy 1.4 -max.ploidy 6 -test.purity 0.8 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file /home/zyto/unger/GATK_Exome_Lisa_PureCN/outref/S07604514_Covered.intervals.txt -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -DB.info.flag DB -POPAF.info.field POP_AF -model betabin -post.optimize TRUE -BPPARAM  -log.file /home/zyto/unger/WES_Rezidiv_HNSCC_Clonality/PureCN/results/HL02_R1.final.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -speedup.heuristics <data>
INFO [2021-03-16 21:47:26] Loading coverage files...
INFO [2021-03-16 21:47:36] Found log2-ratio in tumor coverage data.
WARN [2021-03-16 21:47:36] log2-ratio contains outliers < -8, ignoring them...
INFO [2021-03-16 21:47:37] Mean coverages: chrX: 72.91, chrY: 87.35, chr1-22: 128.49.
INFO [2021-03-16 21:47:38] Mean coverages: chrX: 72.91, chrY: 87.35, chr1-22: 128.49.
WARN [2021-03-16 21:47:42] tumor.coverage.file and interval.file do not align.
INFO [2021-03-16 21:47:56] Removing 10 intervals with missing log.ratio.
INFO [2021-03-16 21:47:56] Using 267333 intervals (267333 on-target, 0 off-target).
INFO [2021-03-16 21:47:56] No off-target intervals. If this is hybrid-capture data, consider adding them.
INFO [2021-03-16 21:47:56] Loading VCF...
INFO [2021-03-16 21:47:58] Found 7450 variants in VCF file.
INFO [2021-03-16 21:47:58] Removing 231 triallelic sites.
WARN [2021-03-16 21:47:58] Found GERMQ info field with Phred scaled germline probabilities.
WARN [2021-03-16 21:47:58] vcf.file has no DB info field for membership in germline databases. Found and used somatic status instead.
INFO [2021-03-16 21:47:58] 240 (3.3%) variants annotated as likely germline (DB INFO flag).
INFO [2021-03-16 21:47:58] HL02_R2.final is tumor in VCF file.
INFO [2021-03-16 21:47:58] No homozygous variants in VCF, provide unfiltered VCF.
INFO [2021-03-16 21:47:58] Detected MuTect2 VCF.
INFO [2021-03-16 21:47:58] Removing 6202 Mutect2 calls due to blacklisted failure reasons.
INFO [2021-03-16 21:47:58] Removing 30 non heterozygous (in matched normal) germline SNPs.
INFO [2021-03-16 21:47:59] Removing 258 variants with AF < 0.030 or AF >= 1.000 or less than 4 supporting reads or depth < 15.
INFO [2021-03-16 21:48:04] Removing 73 blacklisted variants.
WARN [2021-03-16 21:48:04] Variant ids contain NAs at filter step BQ.
INFO [2021-03-16 21:48:04] Removing 0 low quality variants with BQ < 25.
INFO [2021-03-16 21:48:04] Total size of targeted genomic region: 57.76Mb (78.07Mb with 50bp padding).
INFO [2021-03-16 21:48:04] 0.2% of targets contain variants.
INFO [2021-03-16 21:48:04] Removing 180 variants outside intervals.
WARN [2021-03-16 21:48:04] Less than half of variants in dbSNP. Make sure that VCF contains both germline and somatic variants.
INFO [2021-03-16 21:48:04] Found SOMATIC annotation in VCF.
INFO [2021-03-16 21:48:04] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2021-03-16 21:48:04] Found SOMATIC annotation in VCF. Setting mapping bias to NaN.
INFO [2021-03-16 21:48:04] Excluding 476 novel or poor quality variants from segmentation.
INFO [2021-03-16 21:48:04] Sample sex: M
INFO [2021-03-16 21:48:04] Segmenting data...
INFO [2021-03-16 21:48:04] Loaded provided segmentation file HL02_R1.final.seg (format DNAcopy).
WARN [2021-03-16 21:48:04] Removing 1 short segments with log-ratio < -8.
INFO [2021-03-16 21:48:04] Re-centering provided segment means (offset -0.0612).
INFO [2021-03-16 21:48:05] Setting prune.hclust.h parameter to 0.150000.
INFO [2021-03-16 21:48:05] Found 160 segments with median size of 3.81Mb.
INFO [2021-03-16 21:48:05] Removing 4 variants outside segments.
INFO [2021-03-16 21:48:05] Using 472 variants.
INFO [2021-03-16 21:48:06] Mean standard deviation of log-ratios: 0.26
INFO [2021-03-16 21:48:06] 2D-grid search of purity and ploidy...
INFO [2021-03-16 21:48:15] Local optima: 0.8/4.4, 0.8/5.2, 0.8/3.6, 0.8/5.8, 0.8/2.8, 0.8/2.1,
0.8/1.4
INFO [2021-03-16 21:48:15] Testing local optimum 1/7 at purity 0.80 and total ploidy 4.40...
INFO [2021-03-16 21:48:27] Testing local optimum 2/7 at purity 0.80 and total ploidy 5.20...
INFO [2021-03-16 21:48:41] Testing local optimum 3/7 at purity 0.80 and total ploidy 3.60...
INFO [2021-03-16 21:48:51] Testing local optimum 4/7 at purity 0.80 and total ploidy 5.80...
INFO [2021-03-16 21:49:05] Testing local optimum 5/7 at purity 0.80 and total ploidy 2.80...
INFO [2021-03-16 21:49:16] Testing local optimum 6/7 at purity 0.80 and total ploidy 2.10...
INFO [2021-03-16 21:49:26] Testing local optimum 7/7 at purity 0.80 and total ploidy 1.40...
INFO [2021-03-16 21:49:31] Recalibrating log-ratios...
INFO [2021-03-16 21:49:31] Testing local optimum 7/7 at purity 0.80 and total ploidy 1.40...
INFO [2021-03-16 21:49:36] Recalibrating log-ratios...
INFO [2021-03-16 21:49:36] Testing local optimum 7/7 at purity 0.80 and total ploidy 1.40...
INFO [2021-03-16 21:49:41] Recalibrating log-ratios...
INFO [2021-03-16 21:49:41] Testing local optimum 7/7 at purity 0.80 and total ploidy 1.40...
INFO [2021-03-16 21:49:46] Skipping 1 solutions that converged to the same optima.
INFO [2021-03-16 21:49:46] Skipping 1 solutions exceeding max.non.clonal (0.20).
INFO [2021-03-16 21:49:46] Fitting variants with betabin model for local optimum 1/7...
INFO [2021-03-16 21:49:49] Fitting variants for purity 0.80, tumor ploidy 4.85 and contamination 0.01.

and error:

[W::hts_idx_load2] The index file is older than the data file: /home/zyto/unger/mutect2_snakemake/results_arch/HL02_Rez.final/filtered_all.vcf.gz.tbi
Error in if (is.na(posterior) || posterior < 0.5) flag <- TRUE :
  missing value where TRUE/FALSE needed
Calls: runAbsoluteCN ... .calcMsSegment -> lapply -> lapply -> FUN -> .calcMsSegmentC
In addition: Warning message:
In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
Execution halted

**Comment by lima1** [comment]
@kristianunger , by default, Mutect2 does not call germline sites when you run it in tumor/normal mode. Activate the —genotype-... flags to get those SNPs. This should put

INFO [2021-03-16 21:48:04] 0.2% of targets contain variants.

above 10%.

**Comment by lima1** [comment]
@drmrgd , seems like the same issue:

WARN [2021-03-15 09:12:21] Less than half of variants in dbSNP. Make sure that VCF contains both germline and somatic variants.

**Comment by kristianunger** [comment]
@lima1 

> @kristianunger , by default, Mutect2 does not call germline sites when you run it in tumor/normal mode. Activate the —genotype-... flags to get those SNPs. This should put
> 
> INFO [2021-03-16 21:48:04] 0.2% of targets contain variants.
> 
> above 10%.

That might explain a lot! I am sure it will work including the genotype flags. Will let you know here.

**Comment by kristianunger** [comment]
> @kristianunger , by default, Mutect2 does not call germline sites when you run it in tumor/normal mode. Activate the —genotype-... flags to get those SNPs. This should put
> 
> INFO [2021-03-16 21:48:04] 0.2% of targets contain variants.
> 
> above 10%.

Your suggestion to include the germline flags into the Mutect2 call In fact did the trick! Thank you!

**Comment by lima1** [comment]
@kristianunger , if you install the https://github.com/nalinigans/GenomicsDB-R package, you can easily use your GATK4 GenomicsDB variant pool of normals for PureCN as well. That's not super critical when you have matched normals, but should improve things a little bit, especially with --model betabin. Essentially this examines the variant allelic fraction distributions in your normal samples and uses them then in the likelihood model.

**Comment by drmrgd** [comment]
Thanks @lima1 for the suggestion and pointing out the missing germline calls.  I need to re-variant call these data to regain the germline calls that were filtered out.  But, since I didn't create these in the first place, and there are some other internal complications, it will be some time until I can get back.  Since it seems to have solved @kristianunger 's issue, I think it will likely solve mine too, and I suppose this issue can therefore be closed.  I really appreciate the help!
