### ISSUE TITLE
clarification on Tumor-only vs. Tumor/Normal-paired PureCN execution

### ISSUE THREAD

**Issue by briandiamondage-sema4** [lima1/PureCN#175]
Hi,

I just wanted to confirm that the difference between tumor-only PureCN vs. matched T/Normal execution is restricted to the Mutect1 vcf file being used - in the former, it's T-only M1 vcf and in T/N-paired it's the M1 T/N-paired vcf.  The other input parameters are essentially the same, and in the T/N-paired situation, the matched normal coverage information isn't being used. Instead, both T-only and T/N-paired both rely on the panel of normals.

When we've run PureCN in T-only and T/N-paired modes this way, the PureCN purity estimates are virtually identical (plot below)
<img width="693" alt="Screen Shot 2021-04-24 at 9 26 19 AM" src="https://user-images.githubusercontent.com/56320955/115960405-38a60a00-a4df-11eb-8fe5-d7f419cef718.png">
.

Thx in advance for your guidance.

(tagging collaborator @Huan-Wang-S4)

**Comment by lima1** [comment]
Yes, that's how these plots usually look. Since most variants are common SNPs and in the VCF flagged as such, there are not too many variants where PureCN most establish the germline status. So not a huge difference from the side.

If you provide a matched normal in the VCF, PureCN can also remove mapping artifacts a bit better, for example if a variant has a low allele frequency in both tumor and normal, it is removed instead of being labelled likely somatic. 

And yes, panel of normal coverage normalization is way better.

**Comment by briandiamondage-sema4** [comment]
Terrific.  Many thanks!
