### ISSUE TITLE
Purity and ploidy values plot accuracy?

### ISSUE THREAD

**Issue by dhsamp** [lima1/PureCN#177]
Hi,

I ran PureCN using the best practices document on an in-house simulated WES sample Tumor-only mode with a panel of normals containing 5 samples from same assay as input sample. The tool ran several iterations of ploidy but reported only 1 in the .csv file. On what basis, this is chosen? This is a simulated sample and I am aware of the right purity and ploidy which is 0.9 and ploidy 2. In my case but the tool chose 0.56 purity and ploidy 4.2 instead when it did have the closest truth (#7 iteration) according to the attached plot. I used a mutect2 tumor-only VCF here. How to interpret this?

Thanks for your help!

[vcfrate0.9_T_local_optima.pdf](https://github.com/lima1/PureCN/files/6442118/vcfrate0.9_T_local_optima.pdf)
[vcfrate0.9_T.pdf](https://github.com/lima1/PureCN/files/6442189/vcfrate0.9_T.pdf)

**Comment by lima1** [comment]
Hi Dharanya,

how did you simulate this sample? It looks pretty noisy. You have these thousands of variants with low allelic fraction close to 0 and the copy number is also relatively noisy.

In my experience it's pretty hard to do a simulation properly. But with a bit of experience it's pretty easy to see if PureCN got it right on real samples.

High ploidy solutions can be wrongly preferred by the model in noisy data because they are more complex and thus can explain the noise better.

Markus

**Comment by dhsamp** [comment]
Hi Markus,

We used PSiTE to simulate this data. I am comparing different copy number callers here and for tumor-normal scenario have had so far almost accurate results matching to the simulated purity - CloneCNA, Sclust, ASCAT and FACETS all performed better for tumor-normal scenarios. But for our tumor-only scenario, I don't have any tool performing better which made me look into PureCN. 

Is there something in the detailed vignette to normalize or reduce the noise before running pureCN? 
How do you evaluate the purity on real samples when the purity is unknown?

Thanks,
Dharanya

**Comment by lima1** [comment]
Can you share the log file of this run?

**Comment by dhsamp** [comment]
Here you go.

[vcfrate0.9_T.log](https://github.com/lima1/PureCN/files/6444743/vcfrate0.9_T.log)

**Comment by lima1** [comment]
Ok, a few things we would highly recommend in a production setting (see Best Practices vignette) that is different from your simulation:

- Coverage normalization against a pool of normals, not against the matched normal. that usually makes a huge difference.
- Run Mutect with a 50-100bp interval padding to get SNPs in the flanking regions
- Generation of a mapping bias file. That means run Mutect with same parameters as for tumor samples on all normal samples. Combine the resulting VCFs (either into a multi-sample VCF or a GenomicsDB - the latter requires the genomicsdb R package from GitHub).

- only 8,635 out of 6,4579 variants are common germline. For whole exome with 50bp padding, I would expect at least 20,000 informative (heterozygous) SNPs. The huge number of novel variants isn't realistic (tumor mutation burden > 1,000/Mb, one order of magnitude higher than most MSI-H samples). If those are simulated, maybe reduce the rate. You can also filter (sub-clonal) somatic mutations if variant classification is not of interest.
- Try the PSCBS segmentation
- You can also try the latest GitHub, which provides the GATK4 segmentation (requires the gatk binary in path, 4.2.0.0 recommended).
- The Mean standard deviation of log-ratios should be at most 0.4 for FFPE. 0.3 for fresh frozen. If it's higher and the setup looks otherwise fine, we recommend users to double check sample QC metrics such as duplication rates.

**Comment by lima1** [comment]
Closing for now, feel free to add questions here in case you want more help.
