### ISSUE TITLE
Compute time for calculateBamCoverageByInterval

### ISSUE THREAD

**Issue by venkateshr89** [lima1/PureCN#188]
**Describe the issue**
Compute time issue with calculateBamCoverageByInterval

**To Reproduce**
bam.file <- "/mnt/data/purecn/reads.bam"

interval.file <- "/home/ubuntu/purecn/processinterval"
calculateBamCoverageByInterval(bam.file = bam.file,interval.file = interval.file, output.file = "/home/ubuntu/purecn/coveragebyinterval")

**Expected behavior**
I was able to run calculatebamcoveragebyinterval function with chr21. However when I use whole transcriptome bam file and interval file it runs for several days and fails. Any suggestion to parallelize the process?

**Comment by lima1** [comment]
That’s not normal. How large is the BAM file?  If the file is stored on a network drive, can you copy local and try again? You should get around 100M reads per hour.

**Comment by lima1** [comment]
PureCN supports GATK4 for coverage calculation, so that might be a better way for such large data in the cloud.  I would recommend following the PureCN Best practices vignette, export a BED file in IntervalFile.R and use that one to calculate coverage following GATK4 copy number workflow. Then instead of using the Coverage.R generated coverage files, use the GATK4 ones. Make sure that GATK4 is not merging intervals (there is an option for that), but is using exactly as provided by IntervalFile.R
