### ISSUE TITLE
Inability to complete PON generation using PureCN

### ISSUE THREAD

**Issue by larysa-27** [lima1/PureCN#189]
Inability to complete PON generation using PureCN from the latest bcbio-nexgene toolkit.
Here is the error:
ValueError: Unexpected path for upload: {'path': '/n/scratch3/users/l/lp176/PON/PureCN/pon/work/gemini/mapping_bias_hg38.rds'}
The error file is attached.
[error_34221246.err.zip](https://github.com/lima1/PureCN/files/6887448/error_34221246.err.zip)

**Comment by lima1** [comment]
Hi larysa-27. I unfortunately don't have a lot of experience with the bcbio pipeline, but one issue I see is that the parsing of the bait BED file failed. You can try loading the file (is it maybe cleaned-wgs_calling_regions.hg38.bed.bed ?) R with:

rtracklayer::import(infile) 

Usually the issue is a header that rtracklayer refuses to parse, so remove any header and try importing again.

**Comment by lima1** [comment]
Closing now since this was the main error message, feel free to reach out if you run into more problems.
