### ISSUE TITLE
C.flagged interpretation

### ISSUE THREAD

**Issue by naumenko-sa** [lima1/PureCN#221]
Hi Markus @lima1 !

Could you please clarify the interpretation of C.flagged column in gene-level CNA output?

The documentation says: "C.flagged - Flagged when segment interval weights are low.   RequiresnormalDB. In case multiple segments overlap, C.flagged will be TRUE when any segment is flagged."

What does it mean for interpretation? In the case under review, some genes are C.flagged in some samples, some genes are not, and they have similar seg.mean, number.targets, gene.mean, the only feature that differs is breakpoints (>0), meaning that there are overlapping segments.

Could these C.flagged events be reported along with non-flagged or should they be removed?

Thanks!
Sergey

**Comment by lima1** [comment]
Hi Sergey,

A segment gets flagged when it has a significantly low average weight in the normal database, i.e. high variance of log ratios. So it's in a region where even in normal samples you see quite a bit of noise. It's possible that the flanking region is fine but gets flagged due to where the breakpoint was set, but yes, I would be careful here.

I don't use that feature that much though to be honest, but I have the luxury of a large collection of cfDNA samples without tumor and I use those for creating blacklists of difficult regions.

Markus
