### ISSUE TITLE
Interpretation of results

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#234]
HI,
Could you please help me to understand the output result for SNV below?
![image](https://user-images.githubusercontent.com/92018021/166881806-e4984105-01c8-4849-8efe-e645e6bd4eb3.png)
Total CN is 2, major and minor allele should be 1, but multiplicity is 2, and is LOH  region? The purity predicted by pureCN is 32% and it has a POOR GOF (72%).

Thank you for help!

**Comment by lima1** [comment]
Yes, that's unlikely correct. Multiplicity of 2 happens when a mutation occurred before a copy number gain. But since there is no copy number LOH, that's unlikely. Have a look at Somatic.M1 vs M2. Maybe there is not a huge difference in confidence, especially when the coverage is low-ish.

See this as a tool to help explaining allelic fractions given copy number, purity and ploidy. If those 3 are potentially off by quite a bit, then the probabilities aren't reliable.

**Comment by maxanes** [comment]
Thank you for the help :)
