### ISSUE TITLE
Pon of normals (NORMAL_PANEL)

### ISSUE THREAD

**Issue by monolo90** [lima1/PureCN#237]
Hello Markus,

How create normal panel from PureCN ?? In the description need only the AD but mutect2 and CreateSomaticPanelOfNormals has other format:

chr16	61946583	.	AAT	TAT,A	.	.	BETA=1.00,1.00;FRACTION=1.00
chr16	61946587	.	G	C,GTCTGC	.	.	BETA=1.00,1.00;FRACTION=1.00
chr16	61946641	.	G	C,*	.	.	BETA=1.00,1.00;FRACTION=1.00

Is correct if i used mutect2 in tumor-only mode with normal samples and then use Mergevcf with min of 5 samples ??

**Comment by lima1** [comment]
Hi,

I would recommend to use the GenomicsDB import. So follow the Mutect2 best practices tutorial closely (add the genotype-germline-sites flag for tumor/normal pairs) and then use  `--normal-panel $GENOMICSDB-WORKSPACE-PATH/pon_db` in NormalDB.R. Installing the genomicsdb R package is a bit of a pain, so I would recommend to do that step in our Docker image.

Markus

**Comment by monolo90** [comment]
Hi Markus

The vcf with Mutec2 with germline-sites flag for tumor/normal pairs is crearly ... but the problem is that pon of normal in best practice somatic use a tumor-only vcf (only normal samples) in mutect 2 and  run `$GENOMICSDB-WORKSPACE-PATH/pon_db`, correct ?? 

I used other alternative solution:

     gatk SelectVariants \
     -R Homo_sapiens_assembly38.fasta \
     -V `$GENOMICSDB-WORKSPACE-PATH/pon_db` \
     -L interval_list \
     -O pon_db_WITH_AD.vcf

Why use this solution ? i cant use docker in my cluster and the vcf from gatk CreateSomaticPanelofNormals don't have AD information in the vcf. Can i use this vcf ?? i suppose yes ... :(


Manuel Muñoz

**Comment by lima1** [comment]
If you are allowed to copy the GenomicsDB to a machine with Docker, I would recommend that. You only need to run NormalDB.R once.

The only supported alternative to GenomicsDB is a multi-sample VCF that contains the AD field for all samples. This step is looking for deviations from the expected allelic fraction of 0.5 for all heterozygous SNPs, so it needs the actual read counts.

There are plenty of tools to combine VCFs into a multi-sample VCF. I haven't looked at a GATK4 solution because of the GenomicsDB support, but see [here](https://github.com/lima1/PureCN/blob/master/vignettes/PureCN.Rnw#L1623-L1639) for a GATK3 solution.

Markus

**Comment by miachom** [comment]
Hi @lima1,

I am confused about how to have a PON for a tumor-only run. I don't have matched normals for my 4 tumor samples and I tried to use publicly available PON such as MuTect2.PON.5210.vcf, MuTect2.PON.4136.vcf and 1000g_pon.hg38.vcf.gz. But none of these work may be because they don't have an AD field tag. I tried to add field tags using "bcftools +fill-tags", but it doesn't add. So in cases like this, how do I use PON that can be used for PureCN run with tumor-only mode?

**Comment by lima1** [comment]
Hi @miachom , PureCN does not require matched normals, but it does require a small number (ideally 5-50, the more the better) normal samples.  That's to learn and remove assay biases. No way around it. So you would need to get normal BAM/FASTQ files from your assay and run them through the same pipeline as tumor samples. Whoever sequenced your samples, ask them if they have healthy control samples. The vendor of the assay might also provide normal BAMs.

**Comment by miachom** [comment]
Hi @lima1, thanks for your quick reply. So when you say PureCN does not require matched normals except to correct for biases, do you mean I can still run PureCN in tumor mode without removing assay biases? Or can I use normal BAMs or FASTQs from other projects if they were run through the same pipeline as tumor samples?

**Comment by lima1** [comment]
You cannot use it without normal BAMs. But yes, any BAM file of the exactly same assay works (you cannot mix say Agilent Exon v4 normals with Exon v6 tumor samples). Ideally from the same lab, but normal BAMs from the vendor can work well enough. There is a FAQ section in the main vignette about normal samples that should provide all details.

**Comment by miachom** [comment]
Hi @lima1, so I already started running PureCN  as a minimal test described section 4.3 of best practices [with](https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/Quick.html) with your recommended advice of using GenomicsDB normal PON generated by `createNormalDatabase`

However, for the production pipeline run, it seems to require a mapping bias file. Hence, in order to generate this mapping bias file from normal vcfs of GATK Mutect2 runs with `calculateMappingBiasVcf(normal.panel.vcf.file, genome = "hg38")`, I am getting errors as-

`INFO [2023-08-21 21:00:34] Processing variants 1 to 50000...
FATAL [2023-08-21 21:00:34] The normal.panel.vcf.file contains only a single sample. 

FATAL [2023-08-21 21:00:34]  

FATAL [2023-08-21 21:00:34] This is most likely a user error due to invalid input data or 

FATAL [2023-08-21 21:00:34] parameters (PureCN 2.6.4). 

Error: The normal.panel.vcf.file contains only a single sample.

This is most likely a user error due to invalid input data or
parameters (PureCN 2.6.4).`

I also get the same error with `genome = "h19`. I am not sure what is causing this error. But I also came across https://github.com/lima1/PureCN/issues/245 where you're saying that if there is an output from either GenomicsDB and VCF in NormalDB then it's all good. So is it like, I can run this production pipeline without mapping bias file generated from `calculateMappingBiasVcf`?
