### ISSUE TITLE
Custom capture and its impact on CNV

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#269]
Hi Markus!

I am starting to analyse data from a custom exome capture where a subset (5%) of target regions have ~ 3-5x higher coverage than the rest of the regions. I have a number of normal samples available for this although I am curious if I can expect the PureCN algorithm to be able to deal with this with default parameter settings? Do you have any suggestions on additional parameters I should consider? 

Thanks!

**Comment by lima1** [comment]
No issue at all and very common. As long as your normals are from the same assay, PureCN's normalization will deal with it. I recommend the betabin model for high coverage, especially if you have >5 normals to build a decent mapping bias database. Otherwise the statistical model will pretty much cap the coverage at 300X.
