### ISSUE TITLE
PureCN and WGS data

### ISSUE THREAD

**Issue by robrollback** [lima1/PureCN#27]
Hi,

I am very interesting in applying this program to our data. We are currently working with WGS pairs and I was curious if there are options/modifications that can be applied to test PureCN on this type of data.  

Thanks for your time.

Best, 
 Rob

**Comment by lima1** [comment]
Hi Rob,

if you have matched tumor/normal, I would use some of the WGS tools like Battenberg, ABSOLUTE, ACEseq, Titan. PureCN is optimized for hybrid capture data and does not utilize high resolution information others do, like SNP phasing, breakpoints at split reads etc. 

For tumor-only, since there is not much out there, you can give it a shot. I would do the segmentation with third-party tools, for example CNVkit. Then be patient, it will be slow. There is at least a --parallel flag now in the new stable.

Markus
