### ISSUE TITLE
Question: Using other variant callers?

### ISSUE THREAD

**Issue by akaviaLab** [lima1/PureCN#308]
**Describe the issue**
My company is having discussions about using variant callers other than Mutect2. One person mentioned that he read (or thinks he read) that PureCN relies on specific parts of the Mutetct2 algorithm or output. Is this correct?
Can we use variant callers in addition to Mutect2?

One discussion we're having is if we're using additional variant callers, is it better to use Intersect or Union for PureCN? In general, we get less False Positives if use Intersect.

If this is in the documentation, I apologize.

Thank you,

Uri David

**Comment by lima1** [comment]
Parsing VCFs is a headache because there is no standard, but PureCN should accept most. As long as it finds the important fields (it will tell you!), you are fine. Make sure to clean the VCFs from artifacts that are not cleaned by a PoN you provide PureCN. Feel free to open an issue with an example VCF that does not work.

**Comment by lima1** [comment]
Not sure about consensus variant calling. Most information comes from common SNPs and modern callers should remove most artifacts. So probably does not matter much.
