### ISSUE TITLE
Question regarding the third-party segmentation file

### ISSUE THREAD

**Issue by maxanes** [lima1/PureCN#347]
Hi,
I have previously asked about WGS data and PureCN usage. I have segmentation output files from Sequenza which seems to do a decent segmentation for WGS data, this is an example of a segmentation file below. Is it possible to use this file in PureCN?
![image](https://github.com/lima1/PureCN/assets/92018021/3f6a0822-7a46-4620-a5a5-abf311ad3450)

Thank you.
Marijana

**Comment by lima1** [comment]
Have a look at the vignette and the input files. PureCN supports DNAcopy (very close to what you have) and GATK4 formats. Sequenza was decent in my benchmarks. If you have matched normals, PureCN doesn't give you much in addition to Sequenza. And the PureCN runtime is long due to the SNP germline vs somatic fitting (you don't need).

**Comment by maxanes** [comment]
Thanks for the advice and quick response. I would like to use pureCN to estimate CCF of mutations. Because it is a WGS data I thought that would be good to use sequenza segmentation file as an input to Purecn to estimate CCFs, if that makes sense.

**Comment by lima1** [comment]
I personally would just use the Sequenza predictions. To get CCFs, you can take a look here: https://github.com/lima1/PureCN/blob/devel/R/PureCN-internal.R#L1073-L1096

**Comment by maxanes** [comment]
Ok, thanks :)
