### ISSUE TITLE
Single standard deviation vs. segment-centric standard deviation for logR likelihood

### ISSUE THREAD

**Issue by tinyheero** [lima1/PureCN#361]
Hi @lima1,

This is more of a question than an issue.

I was re-reading the PureCN paper and reviewing the equation of the original paper (https://scfbm.biomedcentral.com/articles/10.1186/s13029-016-0060-z):

$$
r_{i} \sim N \Bigg(log_{2} \frac{pC_{i} + (1-p)2}{p\Big(\sum_{j}l_{j}C_{j}\Big) / \sum_{j}l_{j} + (1-p)2}, \sigma_{ri} \Bigg)
$$

The standard deviation ($\sigma_{ri}$) of the normal distribution is set to be:

> the average standard deviation of log-ratios in a segment

I am just curious as to what the rationale is for using a single standard deviation value (learned across all segments) rather than have the standard deviation set to be segment-centric?

**Comment by lima1** [comment]
Hi @tinyheero . Since version 1.10, the standard deviation used in this equation is optimized as well during the Simulated Annealing. But still a single one for all segments.  I'm open for suggestions how to improve. The segments will converge to a very similar value with increasing segment size, so I feel it's probably fine. There is some outlier filtering happening, so small segments where segment log ratio differs from global one due to technical reasons still should not have a dramatic impact.

But that part of the code is unchanged for many years, so I can't fully remember every single decision/benchmarking leading to it.

**Comment by tinyheero** [comment]
Thanks @lima1 for your reply. 

I agree that it probably doesn't make much difference.
