### ISSUE TITLE
Missing dependency on optparse

### ISSUE THREAD

**Issue by jbedo** [lima1/PureCN#64]
PureCN has a dependency on optparse which is unstated:

```
$ Rscript PureCN.R
Error in library(optparse) : there is no package called ‘optparse’
```

**Comment by lima1** [comment]
Hi Justin,

it's specified as suggested dependency, because it's not needed by the main package, "only" the command line tools.  

But since the CLI is now recommended, I will add installation instructions to the Quick Vignette that automatically installs those requirements (for example: BiocManager::install("PureCN", dependencies=TRUE)).

Thanks a lot,
Markus

**Comment by jbedo** [comment]
Thanks for the clarification.

**Comment by fi1d18** [comment]
Having this already installed, I get the same error

**Comment by lima1** [comment]
BiocManager::install(c("optparse", "R.utils",
    "TxDb.Hsapiens.UCSC.hg19.knownGene", "org.Hs.eg.db"))

Change to hg38 if necessary.


https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/Quick.html

**Comment by fi1d18** [comment]
Thanks for answering me and sorry for this weird email/request, in advance;

Please, do you have access to GDC portal?

I am trying to run `mutect2` in tumor-only mode on my WES data for which I need a panel of normal (PON)

I have tried

***@***.***:/data/Continuum/WES/vcf$ ./gatk Mutect2 -R resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -I PicMD.bam -O 3.mt2.vcf -tumor PicMD.targeted_sequencing.sample_name --af-of-alleles-not-in-resource 2.5e-06 --germline-resource af-only-gnomad.hg38.vcf.gz -pon somatic-hg38_1000g_pon.hg38.vcf.vcf

Which says


A USER ERROR has occurred: Cannot read file:///data/somatic-hg38_1000g_pon.hg38.vcf.vcf because no suitable codecs found

I know gatk4_mutect2_4136_pon.vcf.gz in the GDC tutorial locates here


https://gdc.cancer.gov/about-data/gdc-data-processing/gdc-reference-files

I have tried

***@***.***:/data/Continuum/WES/vcf$ ./gdc-client download 6c4c4a48-3589-4fc0-b1fd-ce56e88c06e4 -t token.txt

[Errno 2] No such file or directory: '/data/Continuum/WES/vcf/token.txt'

That means I have to register to GDC but postdoctoral researchers can not register

Do you have access to gatk4_mutect2_4136_pon.vcf.gz file please?

If no, do you know how to push mutect2 run with another PON?

Thanks for any help

________________________________
