### ISSUE TITLE
could not load data for PreprocessIntervals function

### ISSUE THREAD

**Issue by nishuai** [lima1/PureCN#83]
When I tried to use PreprocessIntervals function as described in the vignette page 4, it uses an 'import' function to import a  bed file and a mappbility file, I assume the import function comes form the package 'rio' but it does not do the job, can you specify where does this import function come from?

```
intervals <- import(bed.file)
mappability <- import(mappability.file)
```
While the R inbuilt function 'read.table' can load the bed file, when running PreprocessIntervals function like this,

`preprocessIntervals(intervals, reference.file)`

it throws out an error message:

`Error in file_ext(file) : could not find function "file_ext"`

Can you specify where to find this 'file_ext' function?

**Comment by lima1** [comment]
Hi Nishuai,

I would recommend following the "Quick" vignette. This will automatically use the recommended workflow in easy to use shell scripts.

You can see the imports in the NAMESPACE file, but it is rtracklayer for import and tools for file_ext.

If you have problems with the Quick vignette, feel free to ask here. In that case, please attach the output of sessionInfo() and try updating to the latest version 1.14.

(Also, as a side note, reading BED files with read.table will result in an off-by-one bug since BED files are 0-based.)

Best,
Markus

**Comment by nishuai** [comment]
Thank you Markus, I'm trying the 'Quick' version of the vignette and so far so good, I will post back if something arises.
