### ISSUE TITLE
Ideal purity for PureCN somatic variant identification

### ISSUE THREAD

**Issue by waemm** [lima1/PureCN#92]
Hi Markus,

I was looking for some guidelines for collaborators on an ideal purity range that will produce best results with PureCN, it seems to me like anywhere between 35-80% ? I am also curious what in your experience the upper and lower limits are for acceptable results. It seems people here are using purity at 15% with good effect so and you mention it can be used upto 95% purity?

So in summary, my guesses are below, would be good to hear what you think is reasonable given we are aiming for around 200x on a whole exome capture.

Ideal range 35% - 80% 
Acceptable range 15% - 95% 

 Thanks!

**Comment by lima1** [comment]
Depends on your priorities. 

- For tumor-only somatic vs. germline classification, the lower the better (up to the assay limit of detection, see the function calculatePowerDetectSomatic; with 200X average you probably have some hotspots with 100X you want to reliably call, then 15% purity gives you still a power of 0.95 to detect)
- But if you also want to classify sub-clonal vs mono-clonal somatic, aim for higher. 35% to 50% would be perfect if somatic status is unclear, 35% to 95% otherwise (matched tumor/normal or for hotspots).
- For copy number and LOH calling, the higher the better

But yes,  your ranges sound right to me.

Markus

**Comment by waemm** [comment]
Much appreciated Markus!
